name: Convert PDF to Markdown

on:
  push

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ronak_sakhuja_resume.tex
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: ronak_sakhuja_resume.pdf
#     - name: Create Pull Request
#       uses: peter-evans/create-pull-request@v1.6.1
#       env:
#         # The token is built in to actions. No config required.
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         COMMIT_MESSAGE: Add .pdf files.
#         PULL_REQUEST_TITLE: Add .pdf files.
#         PULL_REQUEST_BRANCH: pdf-add
#         PULL_REQUEST_BODY: Here's the PDF File
#         PULL_REQUEST_REVIEWERS: scottypate
